### ISSUE TITLE
Add support for requests.request

### ISSUE THREAD

**Issue by whitfin** [maxzheng/aiohttp-requests#10]
Hi!

Cool library, really reduces the headache moving from `requests` to `aiohttp`. I can see that this supports all of the HTTP verbs, but I'm curious if it'd be possible to support `request(method, url, ...)` too. As far as I can tell, this isn't supported despite it being supported in `aiohttp`? 

Thank you!

**Comment by maxzheng** [comment]
@whitfin Added and released as 0.2.4. Happy requesting!

**Comment by whitfin** [comment]
Awesome, thank you!
