### ISSUE TITLE
How to disable SSL verification?

### ISSUE THREAD

**Issue by hf-kklein** [maxzheng/aiohttp-requests#5]
I'd like to pass an argument to the ClientSession to disable the SSL verification (for a testsystem with selfsigned cert), like described [here](
https://github.com/aio-libs/aiohttp/issues/955#issuecomment-230897285)

```python
session = aiohhtp.ClientSession(connector=aiohttp.TCPConnector(verify_ssl=False))
```
Is there a possibility to pass arguments to the ClientSession with aiohttp-requests?

**Edit**: In case anyone needs this urgently you can modify the "private" variable that stores the session arguments:
```python
from aiohttp_requests import requests
...
requests._session_args[1]["connector"] = aiohttp.TCPConnector(verify_ssl=False)
```

**Comment by maxzheng** [comment]
The proper approach is to create your own `requests` instance from the `Requests` class like: 

>>> from aiohttp_requests import Requests
>>> requests = Requests(connector=aiohttp.TCPConnector(verify_ssl=False))
