### ISSUE TITLE
Breaks other libraries depending on aiohttp

### ISSUE THREAD

**Issue by AlexExarhos** [maxzheng/aiohttp-requests#6]
See this line:
https://github.com/maxzheng/aiohttp-requests/blob/3eb08da05adaf5d78334b1335c38b3f3549c1709/aiohttp_requests/__init__.py#L4

Patching the 'ClientResponse.read' will **break** other libraries that depend on its behavior. My project was also using [aioboto3](https://pypi.org/project/aioboto3/), which led to ClientDisconnect errors.

**Comment by maxzheng** [comment]
Removed monkey patching as it is not absolutely necessary -- it seems to close by itself after reading to EOF or later during garbage collection now. Published change as 0.2.0. Try it and let me know if you still run into problems.
