### ISSUE TITLE
Breaks `aiodocker` because of monkey patching aiohttp

### ISSUE THREAD

**Issue by AndreaCensi** [maxzheng/aiohttp-requests#7]
Similar to the preceding issue #6, this library breaks `aiodocker`.
More details here: https://github.com/aio-libs/aiodocker/issues/706

**Comment by maxzheng** [comment]
Removed monkey patching as it is not absolutely necessary -- it seems to close by itself after reading to EOF or later during garbage collection now. Published change as 0.2.0. Try it and let me know if you still run into problems.
